export const cartActionTypes = {
  TOGGLE_SHOPPING_LIST: 'TOGGLE_SHOPPING_LIST',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
  INC_QTY: 'INC_QTY',
  DEC_QTY: 'DEC_QTY',
  CLEAR_CART: 'CLEAR_CART',
};
